"""
Django settings for Mediaproject project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-development-key-change-this"
)

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Django default applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Our application
    "mediaapp",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "Mediaproject.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "Mediaproject.wsgi.application"


# ============================================================
# DATABASE - POSTGRESQL
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",

        "NAME": os.getenv(
            "DB_NAME",
            "media_processing"
        ),

        "USER": os.getenv(
            "DB_USER",
            "postgres"
        ),

        "PASSWORD": os.getenv(
            "DB_PASSWORD",
            "1234"
        ),

        "HOST": os.getenv(
            "DB_HOST",
            "localhost"
        ),

        "PORT": os.getenv(
            "DB_PORT",
            "5432"
        ),
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"


# Folder where we keep our CSS/JS files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Folder used when collecting static files
STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# MEDIA FILES
# ============================================================

# URL used to access uploaded files
MEDIA_URL = "/media/"


# Physical folder where uploaded files are stored
MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# CELERY CONFIGURATION
# ============================================================

# Redis is our message broker.
#
# Django
#    ↓
# Celery
#    ↓
# Redis
#    ↓
# Celery Worker

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/0"
)


# Redis stores Celery task results
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    "redis://127.0.0.1:6379/0"
)


# Only JSON data is accepted
CELERY_ACCEPT_CONTENT = [
    "json",
]


# Task serialization
CELERY_TASK_SERIALIZER = "json"


# Result serialization
CELERY_RESULT_SERIALIZER = "json"


# Celery timezone
CELERY_TIMEZONE = "Asia/Kolkata"


# Track when a task starts
CELERY_TASK_TRACK_STARTED = True


# Maximum task execution time
# 30 minutes
CELERY_TASK_TIME_LIMIT = 30 * 60


# Soft time limit
# 25 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60


# Worker processes one task at a time
# before requesting more tasks
CELERY_WORKER_PREFETCH_MULTIPLIER = 1


# Acknowledgement happens after task execution
CELERY_TASK_ACKS_LATE = True


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"